= First steps with programming Bluetooth Low Energy devices
Maxime Lefrançois maxime.lefrancois@emse.fr v1.0, 2022-12-01
:homepage: http://ci.mines-stetienne.fr/cps2/course/pcd/
:toc: left

In this lab you will develop your first BLE applications.

== Introduction to the Adafruit Feather Bluefruit Sense

For MicroPython, use the link:https://github.com/micropython/micropython-lib/tree/master/micropython/bluetooth[`aioble` library].

For CircuitPython, look at the link:https://learn.adafruit.com/adafruit-feather-sense/getting-started-with-ble-and-circuitpython[examples in the documentation]

The slides of link:https://ci.mines-stetienne.fr/cps2/course/pcd/#_part_7_low_power_wireless_personal_area_networks_lowpan[_Lecture 7 LoWPAN_] may be useful, together with the following Bluetooth specification documents:

* link:docs/Mesh%20Model%201.0.1.pdf[Bluetooth Mesh Model 1.0.1 Specification]: defines models (along with their required states and messages) that are used to perform basic functionality on the nodes in a mesh network beyond the foundation models defined in the Bluetooth Mesh Profile specification [2]. This specification includes generic models defining functionality that is standard across device types, and models, such as lighting control, sensors, and time and scenes, to support key mesh scenarios.
* link:docs/Mesh%20Profile%201.0.1.pdf[Bluetooth Mesh Profile 1.0.1 Specification]: defines fundamental requirements to enable an interoperable mesh networking solution for Bluetooth low energy wireless technology.
* link:docs/Mesh%20Device%20Properties%202.pdf[Bluetooth Mesh Device Properties 2 Specification]: contains definitions of device properties that are required by the Bluetooth Mesh Profile and Bluetooth Mesh Model specifications.
* link:docs/Assigned-Numbers-2022-11-28.pdf[Bluetooth Assigned Numbers]: a regularly updated document listing assigned numbers, codes, and identifiers in the Bluetooth specifications.


Browse these specifications and the link:https://github.com/micropython/micropython-lib/blob/master/micropython/bluetooth/aioble/examples/temp_sensor.py[aioble `temp_sensor.py` example]. Answer the following questions.

1. **In what document(s) can you find the specification of the `org.bluetooth.service.environmental_sensing` service?** 
2. **What is the format of the `org.bluetooth.characteristic.temperature` characteristic according to the specification?**
3. **How are the appearance UUIDs used by BLE clients such as your phone?**
4. **Find appropriate BLE services and characteristics for the sensors you have, given your project**

_(edit this file and write your answers here)_

Answers:

1. In documents Mesh Profile 1.0.1 Specification and Mesh Device Properties 2 Specifications.

2. The first value - average ambient temperature as measured during a period of time, the second value - start of the period, and the third value - end of the period.

3. 

Install the **nRF Connect** application on your smartphone, and make so that your device behaves as a valid BLE peripheral.

Develop a BLE client to access the BLE peripheral.



== Next steps

Next your will just finalise your integrated project. Move to `project.adoc`


